package hr.mrodek.apps.bela_turniri.model;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * One finished online Bela game, as reported by the Node game server
 * (game/README.md §8).
 *
 * <p>The backend is a recorder, not a judge: the reporting server decides
 * whether a game is eligible (§8.1 — it counts only when BOTH teams contain
 * at least one human, which the game server knows per seat and the backend
 * does not) and hands that verdict over in {@link #eligible}.
 *
 * <p>Since 2026-09-22 (§8.7) it reports every finished game that had at least
 * one real person at the table, eligible or not, so the admin analytics can
 * see games played against bots and against the demo lobby's fake people.
 * {@code eligible} is what keeps the two apart: the competitive reads
 * (profile statistics, the karma window) filter on it, the analytics reads
 * deliberately do not.
 *
 * <p>{@link #uuid} is the idempotency key, minted once per game by the
 * reporter and resent verbatim on a retry. It is UNIQUE, and that index is
 * the whole concurrency gate — the write path inserts with
 * {@code ON CONFLICT (uuid) DO NOTHING} rather than catching a violation,
 * for the same reason {@code IdempotencyService} does: a JPA constraint
 * violation dooms the persistence context and leaves no way to recover
 * inside the same transaction.
 *
 * <p>No aggregate/counter columns anywhere: statistics are always computed
 * by query from {@link GameResultPlayer} rows.
 */
@Entity
@Table(name = "game_results")
@Getter @Setter @NoArgsConstructor
public class GameResult {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Idempotency key generated by the reporting game server. */
    @Column(name = "uuid", nullable = false, unique = true)
    private UUID uuid;

    @Column(name = "played_at", nullable = false)
    private OffsetDateTime playedAt;

    /** Category: 163, 501, 701 or 1001 (game/README.md §8.2). */
    @Column(name = "target_score", nullable = false)
    private short targetScore;

    /** {@code "A"} or {@code "B"} — CHAR(1) in the schema. */
    // columnDefinition, not length: the schema column is CHAR(1) and a plain
    // length=1 makes Hibernate expect VARCHAR(1), which dev-mode validation flags.
    @Column(name = "winner_team", nullable = false, columnDefinition = "char(1)")
    private String winnerTeam;

    @Column(name = "score_a", nullable = false)
    private int scoreA;

    @Column(name = "score_b", nullable = false)
    private int scoreB;

    /** Number of deals played. Informational; the reporter may omit it. */
    @Column(name = "deals_count")
    private Short dealsCount;

    /**
     * §8.1's verdict: does this game count for the competitive record?
     *
     * <p>Nullable in the schema (an older game server posts a body without
     * it, and every row written before 2026-09-22 predates the column), so
     * every query that filters on it uses {@code eligible = true} — a NULL
     * never matches, and the changeset backfills the old rows to TRUE rather
     * than leaving the reads to guess.
     */
    @Column(name = "eligible")
    private Boolean eligible;

    /**
     * The four seats. {@code CascadeType.ALL} + {@code orphanRemoval} mirror
     * the FK's {@code ON DELETE CASCADE}, so removing a result through JPA
     * behaves the same as removing it in SQL.
     */
    @OneToMany(mappedBy = "gameResult", cascade = CascadeType.ALL,
            orphanRemoval = true, fetch = FetchType.LAZY)
    private List<GameResultPlayer> players = new ArrayList<>();
}
